import type { ReactNode } from 'react'
import katex from 'katex'
import 'katex/dist/katex.min.css'
import { cn } from '@/utils/classNames'

/**
 * Minimal Markdown renderer used for course notes and lesson content.
 *
 * No external markdown dependency — it supports headings, bullet & numbered
 * lists, HR, paragraphs, inline emphasis (`**bold**`, `*italic*`, `` `code` ``)
 * and LaTeX math via KaTeX:
 *   - ``$...$``   inline math, e.g. ``$x^2 + y^2 = z^2$``
 *   - ``$$...$$`` block (display) math, e.g. ``$$\frac{3}{4}$$``
 * Math is generated by KaTeX (its own sanitized output) and injected into
 * ``dangerouslySetInnerHTML`` spans — no user-supplied HTML/Script can run.
 */

function renderKaTeX(expr: string, displayMode: boolean): string {
  try {
    return katex.renderToString(expr, { throwOnError: false, displayMode })
  } catch {
    return expr
  }
}

// Math first so `$a*b$` is captured whole before the emphasis `*...*` rule.
// Math is `$...$` on a single line (no newline inside).
const INLINE_RE = /([$][^$\n]+[$]|\*\*[^*]+\*\*|`[^`]+`|\*[^*]+\*)/g

function isMathToken(token: string): boolean {
  return token.length > 2 && token.startsWith('$') && token.endsWith('$')
}

function renderInline(source: string, keyPrefix: string): ReactNode[] {
  const nodes: ReactNode[] = []
  let last = 0
  let m: RegExpExecArray | null
  let k = 0
  while ((m = INLINE_RE.exec(source)) !== null) {
    const token = m[0]
    if (m.index > last) nodes.push(source.slice(last, m.index))
    const key = `${keyPrefix}-${k++}`
    if (isMathToken(token)) {
      nodes.push(
        <span
          key={key}
          dangerouslySetInnerHTML={{ __html: renderKaTeX(token.slice(1, -1), false) }}
        />,
      )
    } else if (token.startsWith('**') && token.endsWith('**') && token.length > 4) {
      nodes.push(<strong key={key}>{token.slice(2, -2)}</strong>)
    } else if (token.startsWith('`') && token.endsWith('`') && token.length > 2) {
      nodes.push(
        <code key={key} className="rounded bg-gray-100 dark:bg-gray-800 px-1 py-0.5 font-mono text-[0.9em]">
          {token.slice(1, -1)}
        </code>,
      )
    } else if (token.startsWith('*') && token.endsWith('*') && token.length > 2) {
      nodes.push(<em key={key}>{token.slice(1, -1)}</em>)
    } else {
      nodes.push(token)
    }
    last = m.index + token.length
  }
  if (last < source.length) nodes.push(source.slice(last))
  return nodes
}

interface ListBuf {
  kind: 'ul' | 'ol'
  items: string[]
}

function mathBlock(key: string, expr: string): ReactNode {
  return (
    <div
      key={key}
      className="katex-block overflow-x-auto py-1"
      dangerouslySetInnerHTML={{ __html: renderKaTeX(expr, true) }}
    />
  )
}

export function Markdown({ text, className }: { text?: string; className?: string }) {
  if (!text) return null
  const lines = text.replace(/\r\n/g, '\n').split('\n')
  const blocks: ReactNode[] = []
  let list: ListBuf | null = null
  let mathBuf: string | null = null

  const flush = (key: string) => {
    if (list) {
      const buf = list
      if (buf.kind === 'ul') {
        blocks.push(
          <ul key={key} className="list-disc pl-6 space-y-3 text-base md:text-lg leading-8 text-slate-700 dark:text-slate-200">
            {buf.items.map((it, i) => (
              <li key={i} className="marker:text-brand-blue">{renderInline(it, `ul-${i}`)}</li>
            ))}
          </ul>,
        )
      } else {
        blocks.push(
          <ol key={key} className="list-decimal pl-6 space-y-3 text-base md:text-lg leading-8 text-slate-700 dark:text-slate-200">
            {buf.items.map((it, i) => (
              <li key={i} className="marker:text-brand-blue">{renderInline(it, `ol-${i}`)}</li>
            ))}
          </ol>,
        )
      }
      list = null
    }
    if (mathBuf !== null) {
      blocks.push(mathBlock(key, mathBuf))
      mathBuf = null
    }
  }
  lines.forEach((rawLine, idx) => {
    const line = rawLine.trim()

    // Accumulate a $$ ... $$ display-math block that may span multiple lines.
    if (mathBuf !== null) {
      if (line.endsWith('$$')) {
        mathBuf += line.slice(0, -2)
        flush(`math-${idx}`)
      } else {
        mathBuf += line + '\n'
      }
      return
    }
    if (line.startsWith('$$')) {
      const rest = line.slice(2)
      if (rest.endsWith('$$') && rest.length > 0) {
        flush(`before-${idx}`)
        blocks.push(mathBlock(String(idx), rest.slice(0, -2)))
      } else {
        flush(`before-${idx}`)
        mathBuf = rest
      }
      return
    }

    if (!line) {
      flush(`list-${idx}`)
      return
    }

    const heading = /^(#{1,3})\s+(.*)$/.exec(line)
    if (heading) {
      flush(`list-${idx}`)
      const level = heading[1].length
      const content = renderInline(heading[2], `h-${idx}`)
      if (level === 1) blocks.push(<h2 key={idx} className="mt-6 mb-3 text-2xl sm:text-3xl font-black tracking-tight text-slate-900 dark:text-white">{content}</h2>)
      else if (level === 2) blocks.push(<h3 key={idx} className="mt-5 mb-2 text-xl sm:text-2xl font-bold text-slate-800 dark:text-slate-100">{content}</h3>)
      else blocks.push(<h4 key={idx} className="mt-4 mb-2 text-lg font-bold text-slate-800 dark:text-slate-100">{content}</h4>)
      return
    }

    if (/^-{3,}$/.test(line)) {
      flush(`list-${idx}`)
      blocks.push(<hr key={idx} className="my-4 border-gray-200 dark:border-gray-700" />)
      return
    }

    const ulMatch = /^[-*]\s+(.*)$/.exec(line)
    if (ulMatch) {
      if (list && list.kind === 'ul') list.items.push(ulMatch[1])
      else {
        flush(`list-${idx}`)
        list = { kind: 'ul', items: [ulMatch[1]] }
      }
      return
    }

    const olMatch = /^\d+[.)]\s+(.*)$/.exec(line)
    if (olMatch) {
      if (list && list.kind === 'ol') list.items.push(olMatch[1])
      else {
        flush(`list-${idx}`)
        list = { kind: 'ol', items: [olMatch[1]] }
      }
      return
    }

    flush(`list-${idx}`)
    blocks.push(
      <p
        key={idx}
        className="mb-2 text-base md:text-lg leading-8 text-slate-700 dark:text-slate-200"
      >
        {renderInline(line, `p-${idx}`)}
      </p>,
    )
  })
  flush('list-final')

  return <div className={cn('slide-deck space-y-3', className)}>{blocks}</div>
}
